version: '3.8'

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
      - "5432:5432"
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000
    # command: gunicorn --bind 0.0.0.0:8000 config.wsgi:application
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust